version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/*"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "06:00"
    pull-request-branch-name:
      separator: "-"
