name: Build Docs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main

jobs:
  go:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.go.outputs.version}}
    steps:
      - name: get latest go version
        id: go
        run: |
          echo version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/update-versions-manifest-file/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

  puernya:
    runs-on: ubuntu-latest
    needs: go
    outputs:
      version: ${{steps.puernya.outputs.version}}
    steps:
      - name: Checkout `building`
        uses: actions/checkout@v4
        with:
          repository: PuerNya/sing-box
          ref: building
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{needs.go.outputs.version}}

      - name: get sing-box puernya version
        id: puernya
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box.git
          git fetch --tags sekai
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo version=$version >> $GITHUB_OUTPUT

  docs:
    runs-on: ubuntu-latest
    needs: puernya
    env:
      docs_version: ${{ needs.puernya.outputs.version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: PuerNya/sing-box
          ref: building

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install and build docs
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-static-i18n
          mkdocs build

      - name: Change custom domain
        run: |
          sed -i '/sagernet/s/sing-box.sagernet.org/sing-boxp.dustinwin.top/' ./site/CNAME

      - name: Git push assets to "docs" branch
        run: |
          cd ./site/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b docs
          git add .
          git commit -m "更新 sing-box PuerNya 版 docs 至 ${docs_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin docs

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
