name: Build Docs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
      timezone: "Asia/Shanghai"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

permissions:
  contents: write
  actions: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `reF1nd-testing`
        uses: actions/checkout@v7
        with:
          repository: reF1nd/sing-box
          ref: reF1nd-testing
          fetch-depth: 0

      - name: Get Python version
        run: |
          echo "python_version=$(curl -fsSL https://endoflife.date/api/python.json | jq -r '.[0].latest')" >> "${GITHUB_ENV}"

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.python_version }}

      - name: Get `sing-box reF1nd-Testing` version
        run: echo "ref1nd_version=$(git tag -l --sort=v:refname | grep -Po '^v\K.*(alpha|beta|rc).*-reF1nd.*' | tail -n1)" >> "${GITHUB_ENV}"

      - name: Install and build docs
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-static-i18n
          mkdocs build

      - name: Change custom domain
        run: |
          sed -i '/sagernet/s/sing-box.sagernet.org/sing-boxr.dustinwin.cc.cd/' ./site/CNAME

      - name: Git push assets to "docs" branch
        run: |
          cd ./site/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b docs
          git add .
          git commit -m "更新 sing-box reF1nd 版 docs 至 ${ref1nd_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin docs

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
